test.plugin ("http:handler-command-adapter", "dispatch")
    .should ("run the adapated command")
        .project ("project-a", true, true)
        .init (s => s.hostClass = s.http.defineHandler ("MyHandler"))
        .init (s => s.hostClassName = "")
        .init (s => s.pluginArgs = "git")
        .givenContext ({ data: { gitcommand: "push" } })
        .expectingPropertyToBeOfType ("result.response", "http.responses.Json")
        .expectingPropertyToBe ("result.response.json", { repo: "", all: false })
        .commit ()

    .reset ()
        .project ("project-a", true, true)
        .init (s => s.hostClass = s.http.defineHandler ("MyHandler"))
        .init (s => s.hostClassName = "")
        .init (s => s.pluginArgs = "return-obj")
        .givenContext ()
        .expectingPropertyToBeOfType ("result.response", "http.responses.Json")
        .expectingPropertyToBe ("result.response.json", { value: 100 })
        .commit ()
;
