test.method ("http.Action", "run")
    .should ("process the request")
        .up (s => s.class = s.class.defineSubclass ("Test")
            .onRun (ctx => ctx.root.processed = true)
        )
        .givenContext ()
        .returnsInstanceOf ("Test.Context")
        .expectingPropertyToBe ("args.0.processed", true)
        .expectingPropertyToBeOfType ("args.0.request", "Test.Request")
        .commit ()
;
